POST http://localhost:5010/register
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}
###
POST http://localhost:5010/login
Content-Type: application/json

{
  "username": "adami",
  "name": "Adam Richard",
  "password": "5687989",
  "gender": "male",
  "location": "Detroit"
}
###
POST http://localhost:5011/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "ric"
}
